export const CODEWORK_PRODUCT_NAME = "♛Codework AI客户端";
export const CODEWORK_PROVIDER_NAME = "Codework AI 内部技术应用";
export const CODEWORK_REGISTER_URL = "https://gptproxy.site/register?aff=Kw5y";
export const CODEWORK_FORGOT_PASSWORD_URL = "https://gptproxy.site/forgot-password";
export const CODEWORK_OFFICIAL_ACCOUNT_LABEL = "♛Codework AI 官方账号";
export const CODEWORK_QQ_GROUP_URL = "https://qm.qq.com/q/MZ8RBWihKC";
export const CODEWORK_QQ_QR_URL = "http://115.190.199.191:20080/assets/community/qq-group.png";
export const CODEWORK_WECHAT_QR_URL = "http://115.190.199.191:20080/assets/community/wechat-group.png";
export const CODEWORK_CLIENT_DOWNLOAD_URL = "http://115.190.199.191:20080/download";
export const CODEWORK_ACTIVITY_PORTAL_URL = "http://115.190.199.191:20080/";
export const CODEWORK_API_BASE_URL = "https://gptproxy.site/v1";
export const UPSTREAM_SOURCE_URL = "https://github.com/BigPizzaV3/CodexPlusPlus";
